### PR TITLE
Added fix to update OSC in "send data via"

### LINKED ISSUE #138: Send data via GUi element does not update when enabling OSC
**Describe the bug**
oscilloscope `send data via` GUI widget does not update when choosing options.

**To Reproduce**
enable OSC in the send data drop down and observe the `Send Data Via` GUI element

**Expected behavior**
`Send Data Via` should reflect comma separated selected options

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nitin710**
# Description
- fixes GUI issue where selecting OSC output does not update "send data via" field
# Issues referenced
- closes #138 

# To Test
- Click on the OSC button.
  - The `send data via` field removes the keyword `None` from display

# Screenshots
- image
- image

### CODE REVIEW

**Comment by nitin710** [comment]
Tested working.

File: EmotiBitOscilloscope/src/ofApp.cpp [hunk 1]
```diff
@@ -897,7 +900,25 @@ void ofApp::sendDataSelection(ofAbstractParameter& output) {
 			}
 		}
 	}
-
+	bool isSending = false;
+	// check if we are sending data out on any channel
+	for (int i = 0; i < sendDataList.size(); i++)
```
Comment (nitin710) [inline EmotiBitOscilloscope/src/ofApp.cpp:905]: Maybe, instead of performing another check (and looping through the the options, use the for-loop above to add/remove `None`?
