### PR TITLE
Fix firmware installer apple silicon fix

### LINKED ISSUE #190: ESP32 Feather not detected on M1 mac
**Describe the bug**
The ESP32 Feather detection failed in firmware installer based on this reddit post.
- https://www.reddit.com/r/EmotiBit/comments/11unjh8/trouble_flashing_from_apple_m1_mbp/

The user reports successful operation on intel based macs, but it only fails on M1 macs. The drivers were installed corretly.

**To Reproduce**
1. Try firmware installer on M1 macs.

**Additional context**

### LINKED ISSUE #213: Firmware Installer does not work with Feather M0 (Mac M1 Ventura 13.1)
**Describe the bug**
The Firmware Installer is not detecting the EmotiBit with Feather M0.

**Expected behavior**
Detect EmotiBit and install the firmware onto the EmotiBit.

**Additional details**
- EmotiBit software version: 1.8.1
- EmotiBit firmware version: 1.8.1-TA
- EmotiBit hardware version: V04a
- OS version:

**To Reproduce**
1. Open Firmware Installer
2. Press Space
3. Press reset on EmotiBit (While not in hib)
4. Connect EmotiBit to computer with data capable cable

**Screenshots**

| Open Firmware Installer | Press Space | Connect EmotiBit |
| ------------------------ | ------------ | ----------------- |
| Screenshot 2023-06-12 at 12 25 36 PM | Screenshot 2023-06-12 at 12 30 55 PM | Screenshot 2023-06-12 at 12 31 32 PM |

| when you plug in the Feather M0 into the mac, how does the new port appear in Arduino IDE Tools > Port? |
| --- |
| Screenshot 2023-06-18 at 6 42 18 PM |

1.8.1.fix-firmwareInstallerAppleSiliconFix.2
- https://github.com/EmotiBit/ofxEmotiBit/releases/tag/untagged-5e1dce81185f3d35f02c

Results
| Open Firmware Installer | Press Space | Connect EmotiBit | GUI screen after connecting EmotiBit |
| ------------------------ | ------------ | ----------------- | -------------------------------------- |
| Screenshot 2023-06-18 at 6 52 20 PM | Screenshot 2023-06-18 at 6 52 52 PM | Screenshot 2023-06-18 at 6 53 25 PM | Screenshot 2023-06-18 at 6 53 41 PM |

Still not detecting.

<!--- Dont forget to label the bug appropriately

### LINKED ISSUE #214: Firmware Installer does not work with ESP32 Feather (Mac M1 Ventura 13.1)
**Describe the bug**
The Firmware Installer is not detecting the EmotiBit with ESP32 Feather.

**Expected behavior**
Detect EmotiBit and install the firmware onto the EmotiBit.

**Additional details**
- EmotiBit software version: 1.8.1
- EmotiBit firmware version: 1.8.1
- EmotiBit hardware version: V04a
- OS version:

**To Reproduce**
1. Open Firmware Installer
2. Press Space
3. Press reset on EmotiBit (While not in hib)
4. Connect EmotiBit to computer with data capable cable.

**Screenshots**

| Open Firmware Installer | Press Space | Connect EmotiBit |
| ------------------------ | ------------ | ----------------- |
| Screenshot 2023-06-17 at 2 35 50 PM | Screenshot 2023-06-17 at 2 36 05 PM | Screenshot 2023-06-17 at 2 38 03 PM |

<!--- Dont forget to label the bug appropriately

### PR DESCRIPTION
**Pull request by nitin710**
# Description

- Fixes Issue with Firmware Installer on macBooks with apple silicon
- Issues description
  - 2 ports are detected sequentially for a plug-in (one port is through apple drivers, another through SiLabs drivers)
  - The ports do not have the required description, which was used to filter possible Feather from other device plug-ins.
  - Both new ports are sequentially discarded because of description mismatch
The installer keeps waiting for a new plug-in

# Requirements
- ❗ ❗ [update the dependency before compiling] https://github.com/EmotiBit/ofxSerial/pull/1

# Issues Referenced

- Fixes #190 
- Fixes #213 
- Fixes #214 

# Documentation update
Link to a change in documentation (if any)

# Notes for Reviewer
- None

# Testing

- Tested on M1 mac.

| Device | M1 mac | intel mac | Windows |
|--------|-----------|-----------|------------|
| Feather M0 | ✔️ (change to ofxSerial fixed desc/PID/VID) | ✔️(was originally working)  | ✔️ No issues were flagged and the original logic still exists, so it should work just fine |
| Feather ESP32| ✔️ Tested working | ✔️ Was originally working | ✔️ No issues were flagged and the original logic still exists, so it should work just fine |

## Results

| Stage | Sreengrab |
|-------|-------------|
| On Startup of app |Screenshot 2023-06-08 at 11 28 42 AM|
|After pressing space |Screenshot 2023-06-08 at 11 28 58 AM|
|Plugged in device |Screenshot 2023-06-08 at 11 29 38 AM|
|Finished updating |Screenshot 2023-06-08 at 11 30 03 AM|

## Feature Tests

- Firmware Installer test for Apple Silicon Macs

# Checklist to allow merge
- [ ] All dependent repositories used were on branch `master`
- Software
  - [ ] Get approval from the reviewer
  - [ ] Passed testing on Windows
  - [ ] Passed testing on macOS *(for major changes/GUI changes/ PRs adding files distributed with the EmotiBit software)*
  - [ ] Passed testing on linux (ubuntu) *(for major changes/GUI changes/ PRs adding files distributed with the EmotiBit software)*
  - [ ] Update software bundle version in `ofxEmotiBitVersion.h`

### CODE REVIEW

File: EmotiBitFirmwareInstaller/src/ofApp.cpp [hunk 1]
```diff
@@ -662,13 +670,15 @@ ofApp::Board ofApp::getBoardFromDeviceInfo(ofx::IO::SerialDeviceInfo deviceInfo)
 		if (info.desc.find(espDescIdentifier) != std::string::npos)
 		{
 			// It is ESP!
+			ofLogNotice("Board Detected") << "Feather ESP";
 			return Board::FEATHER_ESP_32;
 		}
 #elif defined TARGET_OSX
-        // if descriptions says silicon labs and port is SLAB_USBtoUART
-        if (info.desc.find(espDescIdentifier) != std::string::npos && info.port.find(espSlabIdentifier) != std::string::npos)
+        // if port is SLAB_USBtoUART
```
Comment (nitin710) [inline EmotiBitFirmwareInstaller/src/ofApp.cpp:677]: This is the main change in the code. 
Everything else is primarily a logging activity.

**Comment by nitin710** [comment]
Esp32 on both intel and apple silicon has been tested.

The Feather M0 is a separate logic and is exclusive to this change. Hence it has not been tested.
