### PR TITLE
Fix data parser

### LINKED ISSUE #97: DataParser: Fix timeSync parsing
# Description
- The TimeSync file is incorrectly parsed if multiple `TL` and `AK` packets are received for the same `RD`

# To recreate Error
- Record data using EmotiBit.
- Parse the recorded data(issue found in v1.4.1)

# Example
- The example below is a timeSync file.
- Each row should ideally have 5 entries(1 for each header column), but since multiple `TL` are received for a single `RD`, the parsing breaks

## Raw data file excerpt
34909 | 1818 | 2 | RD | 1 | 100 | TL | TU
-- | -- | -- | -- | -- | -- | -- | --
34921 | 1819 | 1 | TL | 1 | 100 | 2022-02-03_15-36-33-427125 |  
34930 | 1820 | 2 | AK | 1 | 100 | 918 | RD
34938 | 1821 | 1 | TL | 1 | 100 | 2022-02-03_15-36-38-612039 |  
34942 | 1822 | 2 | AK | 1 | 100 | 1818 | RD

## Expected parsed output
```
RD,TS_received,TS_sent,AK,RoundTrip,
29801,29820,2022-02-03_15-36-33-359625,29823,19,
34909,34938,2022-02-03_15-36-38-612039,34942,29,
40051,40082,2022-02-03_15-36-43-904664,40087,31,
45159,,45195,2022-02-03_15-36-49-154748,45199,36,
50295,50327,2022-02-03_15-36-54-438459,50330,32,
55403,55414,2022-02-03_15-36-54-522252,
60511,60560,2022-02-03_15-37-04-946751,60564,49,
65619,65649,2022-02-03_15-37-10-203132,65652,30,
70751,70781,2022-02-03_15-37-15-484345,70784,30,
75901,75933,2022-02-03_15-37-20-777698,75936,32,
81010,2022-02-03_15-37-26-036774,81044,29,
```
## Actual parsed output:
 ```
RD,TS_received,TS_sent,AK,RoundTrip,
29801,29820,2022-02-03_15-36-33-359625,29823,19,
34909,34921,2022-02-03_15-36-33-427125,34938,2022-02-03_15-36-38-612039,34942,29,
40051,40064,2022-02-03_15-36-38-678828,40082,2022-02-03_15-36-43-904664,40087,31,
45159,45176,2022-02-03_15-36-43-989528,45195,2022-02-03_15-36-49-154748,45199,36,
50295,50308,2022-02-03_15-36-49-229027,50327,2022-02-03_15-36-54-438459,50330,32,
55403,55414,2022-02-03_15-36-54-522252,
60511,60522,2022-02-03_15-36-59-693605,60542,2022-02-03_15-36-59-852869,60560,2022-02-03_15-37-04-946751,60564,49,
65619,65630,2022-02-03_15-37-05-035498,65649,2022-02-03_15-37-10-203132,65652,30,
70751,70763,2022-02-03_15-37-10-267936,70781,2022-02-03_15-37-15-484345,70784,30,
75901,75912,2022-02-03_15-37-15-563744,75933,2022-02-03_15-37-20-777698,75936,32,
81010,81015,2022-02-03_15-37-20-861264,81039,2022-02-03_15-37-26-036774,81044,29,
```

# Code Reference
- https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L485-L486
  - We are writing to the file without checking if the `TL` corresponds to the correct `RD` 

# Fix
Move printing `TL` to the file, inside the "print `AK` block
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L485-L500

### LINKED ISSUE #99: DataParser: Verify all `RD` expected outcomes are being covered
# Description
EmotiBit sends an `RD` packet to the host to get timeSyncs.
- A key point to note, is that the `RD` packet is sent twice.
- Once directly through UDP
  - https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/c1b057ad47a67b620d53924bef54eec50ecc1974/EmotiBitWiFi.cpp#L547
- Second time 
  - it is added to the main SD record out stream
  - https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/c1b057ad47a67b620d53924bef54eec50ecc1974/EmotiBitWiFi.cpp#L550
So, for a single RD, it is possible to receive multiple `TL`-`AK` pairs

- Also, it should be noted that, as of FW v1.3.34, the EmotiBit only reads the UDP channel for 100mS after senfing `RD`. The next UDP read happens when the next `RD` is sent, after ~5s 
https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/c1b057ad47a67b620d53924bef54eec50ecc1974/EmotiBitWiFi.cpp#L558-L595

Example:

34909 | 1818 | 2 | RD | 1 | 100 | TL | TU|
-- | -- | -- | -- | -- | -- | -- | --
34921 | 1819 | 1 | TL | 1 | 100 | 2022-02-03_15-36-33-427125 |  
34930 | 1820 | 2 | AK | 1 | 100 | 918 | RD
34938 | 1821 | 1 | TL | 1 | 100 | 2022-02-03_15-36-38-612039 |  
34942 | 1822 | 2 | AK | 1 | 100 | 1818 | RD|

`34909 | 1818 | 2 | RD | 1 | 100 | TL | TU|`  is the original `RD`

TL response for a previous RD(Note how the RD packet number in AK does not match with the RD
```
34921 | 1819 | 1 | TL | 1 | 100 | 2022-02-03_15-36-33-427125 |  
34930 | 1820 | 2 | AK | 1 | 100 | 918 | RD
```

TL response for the current RD(the RD packet number in AK matches(1818)
```
34938 | 1821 | 1 | TL | 1 | 100 | 2022-02-03_15-36-38-612039 |  
34942 | 1822 | 2 | AK | 1 | 100 | 1818 | RD|
```

We need to make sure we can account for all cases of RD-TL messaging so as to avoid any errors in parsing

# Possible RD-TL scenarios

1. Expected  [✔️ ]timeSyncTableUpdatedCorrectly  | [✔️ ]parsed correctly
```
29801,918,2,RD,1,100,TL,TU
29820,919,1,TL,1,100,2022-02-03_15-36-33-359625
29823,920,2,AK,1,100,918,RD
```
--------------------------------------------------------------------------------------
2. 2 or more TL received for 1 RD   [✔️ ]trimeSyncTableUpdatedCorrectly  | [❌ ]parsed correctly(#97 fixes this)
```
34909,1818,2,RD,1,100,TL,TU
34921,1819,1,TL,1,100,2022-02-03_15-36-33-427125
34930,1820,2,AK,1,100,918,RD
34938,1821,1,TL,1,100,2022-02-03_15-36-38-612039
34942,1822,2,AK,1,100,1818,RD
```
--------------------------------------------------------------------------------------
3. No AK from host   [✔️]timeSyncTableUpdatedCorrectly  | [✔️]parsed correctly
```
29801,918,2,RD,1,100,TL,TU
29820,919,1,TL,1,100,2022-02-03_15-36-33-359625
[UDP loss]
```
RTT will be -1, so this packet will not be considered

--------------------------------------------------------------------------------------
4. No TL from host   [❌]timeSyncTableUpdatedCorrectly  | [❌]parsed correctly #97
```
29801,918,2,RD,1,100,TL,TU
[UDP loss]
29823,920,2,AK,1,100,918,RD
```
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L494
this would result in a negative RTT.
We sort the list of RTTs, so having a `-ve` in the list would be flagged as the smallest RTT(wrong)
which would cause erroneous output as this point would be chosen to create the time mapping, but it does not have any TL sent from the host
Fix: **remove any -ve RTT from the list of RTTs**

--------------------------------------------------------------------------------------
5. Multiple responses, with any **but correct** TL missing   [✔️]timeSyncTableUpdatedCorrectly  | [❌ ]parsed correctly #97
```
34909,1818,2,RD,1,100,TL,TU
[UDP loss]
34930,1820,2,AK,1,100,918,RD
34938,1821,1,TL,1,100,2022-02-03_15-36-38-612039
34942,1822,2,AK,1,100,1818,RD
```
--------------------------------------------------------------------------------------
6. Multiple responses, with **the correct TL** missing   [❌]timeSyncTableUpdatedCorrectly  | [❌]parsed correctly #97
```
34909,1818,2,RD,1,100,TL,TU
34921,1819,1,TL,1,100,2022-02-03_15-36-33-427125
34930,1820,2,AK,1,100,918,RD
[UDP loss]
34942,1822,2,AK,1,100,1818,RD
```
The correct AK would acknowledge a wrong TL.

Suggested fix:
Reset the TL data stored, if a wrong AK is received.
Have an `else` for this `if`
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L492
which resets the `TL` contents in the table
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L480-L482

Suggested solution:
we can fx it by sending TL and AK in the same packet. This way, is the packet is lost we will not get a partial TL.
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/src/EmotiBitWiFiHost.cpp#L477-L498

--------------------------------------------------------------------------------------
7. Multiple responses, with any **but correct** AK missing   [✔️ ]timeSyncTableUpdatedCorrectly  | [❌]parsed correctly #97
```
34909,1818,2,RD,1,100,TL,TU
34921,1819,1,TL,1,100,2022-02-03_15-36-33-427125
[UDP loss] 34930,1820,2,AK,1,100,918,RD
34938,1821,1,TL,1,100,2022-02-03_15-36-38-612039
34942,1822,2,AK,1,100,1818,RD
```
--------------------------------------------------------------------------------------
8. Multiple responses, with **the correct** AK missing   [✔️]timeSyncTableUpdatedCorrectly  | [❌ ]parsed correctly #97
```
34909,1818,2,RD,1,100,TL,TU
34921,1819,1,TL,1,100,2022-02-03_15-36-33-427125
34930,1820,2,AK,1,100,918,RD
34938,1821,1,TL,1,100,2022-02-03_15-36-38-612039
[UDP loss]
```
--------------------------------------------------------------------------------------
9. No response
[✔️]timeSyncTableUpdatedCorrectly  | [✔️ ]parsed correctly

10. received wrong TL and correct AK, but dropped wrong AK
[❌ ]timeSyncTableUpdatedCorrectly  | [✔️ ]parsed correctly
```
34909,1818,2,RD,1,100,TL,TU
34921,1819,1,TL,1,100,2022-02-03_15-36-33-427125
[UDP loss]34930,1820,2,AK,1,100,918,RD
[UDP loss]34938,1821,1,TL,1,100,2022-02-03_15-36-38-612039
34942,1822,2,AK,1,100,1818,RD
```
the right Ak would acknowledge the wrong TL

Fix: Need to tx TL and AK as one UDP packet in the oscilloscope
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/src/EmotiBitWiFiHost.cpp#L476-L498

### LINKED ISSUE #100: DataParser: Change init value of TimeSyncMap
# Description
The initial value of the timeSyncMap should be set to an "impossible value"

https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.h#L106-L107

Right now, `c0` and `c1` are set to 2^31 and 2^32. Here, `^` is a bitwise operator, which inits. c0 = 29(2 XOR 31)  and c1 = 34(2 XOR 32)

# Proposed solution
We should set all values e0,e1,c0 = 0,c1  = 1;
This way, if the parser does break for any un-forseen reason, the generated timestamps would suggest data was collected on `GMT: Thursday, January 1, 1970 12:00:00 AM`

### LINKED ISSUE #101: DataParser: Implement a check for generated TimeSyncMap
# Description
- Right now, there is no check for the returned value of a timesync map
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L193

- In a case when a timeSyncMap cannot be generated, the parser should NOT CONTINUE TO PARSE values
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L246-L249

# Proposed solution
- implement a check for value returned by `calculateTimeSyncMap`
  - If the init value of timeSyncMap.c0 is set to `0`, as proposed in  #100 , we can quit if only one time stamp is received

### LINKED ISSUE #103: DataParser: false "missed packet error"
# Description
When the parser starts parsing a file, it un-conditionally spits out a "missed packet" error in the console.

# To recreate the bug
- parse a file

# Cause
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L433

The first time the parser runs, `packetNumber` can be anything maybe 0, in which case
`tempPacketNumber - packetNumber > 1`

# Fix
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L420
Set `packetNumber` to -1.
Check if packet number = -1, if yes, then its the first line of teh file and skip the  check 
`tempPacketNumber - packetNumber > 1`

### LINKED ISSUE #104: DataParser: false "malformed" packet detected
# Description
The parser falsely detects a "malformed" packet.

# Reason
- If the end of file has a blank line
```
218372,33394,2,AZ,1,100,0.854,0.737
218372,33395,2,GX,1,100,32.471,47.791
218372,33396,2,GY,1,100,79.315,28.809
218372,33397,2,GZ,1,100,-1.556,12.848
218372,33398,2,MX,1,100,-13,-15
218372,33399,2,MY,1,100,-34,-34
218372,33400,2,MZ,1,100,63,63
<blank line>
```
when the parser tries to parse a blank line, it prints the following error
image

There is also a conditional checking "end of file" 
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L170-L176
This causes the parser to print this error 10 times and then continue with the parsing
image

# Fix
- Figure out why we are checking `eof` 10 times
- Implement a check for `if(line = "") return;`
  - https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L419-L422 

# Additional Considerations
> that weird characters caused by a String overflow (or whatever it was) would create a false EOF

> there is still old data with these weird characters, so we need to be mindful to create a solution that doesn't create problems.

### LINKED ISSUE #105: DataParser: verify we are parsing Aperiodic signals correctly
https://github.com/EmotiBit/ofxEmotiBit/blob/2ea8b07a6422bf42fcf4e0883b1729fe8752abb0/EmotiBitDataParser/src/ofApp.cpp#L571-L592

### LINKED ISSUE #110: DataParser: Enable parsing if 0 or 1 timestamps are received
# Description
The parser should be able to handle a case when 0 or 1 timestamps are received.

## Case: when 0 timestamps are received
- e0 = first timestamp in recorded file
- e1 = last timestamp in recorded file
- The created timeline maps emotibit timeline -> epoch timeline as follows
  - e0(start of data record) -> 0
  - e1(end of data record) -> 1

## Case: when 1 timestamp is received
- if timestamp is received closer to the beginning of the recording
  - e0/c0 = timestamp received
  - e1 = last timestamp in recorded file
  - c1 = c0 + (e1-e0)
- if timestamp is received closer to the end of the recording
  - e1/c1 = timestamp received
  - e0 =  first timestamp in the recorded file
  - c0 = c1 - (e1-e0)

### LINKED ISSUE #111: DataParser: Improve user instructions when too few timesyncs are found
# Description
If too few time syncs are found, add user instructions to better educate people how to improve data collection

# Proposed output
```
		std::string instructions = "Less than 2 timesyncs found. Follow these instructions to improve recodring process:\n";
		instructions += "\t1. Allow EmotiBit to be connected to network for as long as possible\n";
		instructions += "\t2. Allow EmotiBit to be connected to Oscilloscope at least for 1 min at the begining and end of record session\n";
```

### PR DESCRIPTION
**Pull request by nitin710**
# Description
Fixes for data parser

# Issues referenced
- Fixes #97 
- Fixes #99
- Fixes #100 
- Fixes #101 
- Fixes #103 
- Fixes #104 
- Fixes #105 
- After Review 1
- Fixes #110 
- Fixes #111 

# Tests
- Refer Each issue to review the test and corresponding result

### CODE REVIEW

File: EmotiBitDataParser/src/ofApp.cpp [hunk 1]
```diff
@@ -417,230 +434,255 @@ void ofApp::exit() {
...
+					if (splitPacket.size() > EmotiBitPacket::headerLength) {
+						// verify if AK is for the correct RD
+						if (lastRDPacketNumber == stoi(splitPacket.at(EmotiBitPacket::headerLength))) {
+							allTimestampData.back().AK = packetHeader.timestamp;
+							allTimestampData.back().roundTrip = allTimestampData.back().TS_received - allTimestampData.back().RD;
+							lastRDPacketNumber = -1; // reset the last RD packet number to avoid overwriting from duplicate
+							auto loggerPtr = loggers.find(timestampFilenameString);
+							if (loggerPtr != loggers.end()) {
+								// write TL information into tiemsync file
+								loggerPtr->second->push(ofToString(allTimestampData.back().TS_received) + ",");
```
Comment (nitin710) [inline EmotiBitDataParser/src/ofApp.cpp:516]: @produceconsumerobot now the timeSyncs file is written only when an `AK` has been received

File: EmotiBitDataParser/src/ofApp.cpp [hunk 2]
```diff
@@ -417,230 +434,255 @@ void ofApp::exit() {
...
+				if (loggerPtr == loggers.end()) {	// we don't have a logger already
+					string outFilePath = inFileDir + inFileBase + "_" + typeTag + fileExt;
+					cout << "Creating file: " << outFilePath << endl;
+					loggers.emplace(typeTag, new LoggerThread("", outFilePath));
+					loggerPtr = loggers.find(typeTag);
+					loggerPtr->second->startThread();
+					loggerPtr->second->push("EpochTimestamp,EmotiBitTimestamp,PacketNumber,DataLength,TypeTag,ProtocolVersion,DataReliability," + typeTag + "\n");
+				}
+				bool isAperiodicType = false;
+				for (int i = 0; i < EmotiBitPacket::TypeTagGroups::NUM_APERIODIC; i++)
```
Comment (nitin710) [inline EmotiBitDataParser/src/ofApp.cpp:604]: new check for aperiodic typetags. check #105 for details

File: EmotiBitDataParser/src/ofApp.cpp [hunk 3]
```diff
@@ -417,230 +434,255 @@ void ofApp::exit() {
...
-	// ToDo: Figure out a way to deal with multiple packets of each number (e.g. UDPx3)
-	packetNumber = tempPacketNumber;
+			// ToDo: Handle 2^32 timestamp rollover (~49 days)
 
-	if (currentState == State::PARSING_TIMESTAMPS) {
-		static int lastRDPacketNumber = -1;
+			if (packetHeader.typeTag.compare(EmotiBitPacket::TypeTag::REQUEST_DATA) == 0) {
+				for (uint16_t i = EmotiBitPacket::headerLength; i < splitPacket.size(); i++) {
+					if (splitPacket.at(i).compare(EmotiBitPacket::TypeTag::TIMESTAMP_LOCAL) == 0) {
+						if (allTimestampData.size() > 0 && allTimestampData.back().roundTrip == -1) {
```
Comment (produceconsumerobot) [inline EmotiBitDataParser/src/ofApp.cpp:467]: I'm a bit confused where allTimestampData.back().roundTrip = -1 is ever set.
I like how it prints the RDs without other values in timesyncs.csv because it gives the user feedback as to when the timesyncs were missed, so it's perhaps a feature to never hit pop_back(), but I'm not sure if this if block is correctly working as intended.
image

**Review by produceconsumerobot — CHANGES_REQUESTED** [review]
Code generally looks good!
Biggest comment is that we should always parse data AND give instructive feedback to the user when timesyncs are limiting.
Additional comments:
- We need to look at parsed data timestamp difference histograms that prove the timestamps are being parsed correctly.
- I thought we were adding some smarts about Q1, Q2, Q3, Q4 selection in calculateTimeSyncMap() in this PR. Is that not the case?

File: EmotiBitDataParser/src/ofApp.cpp [hunk 4]
```diff
@@ -229,19 +240,19 @@ ofApp::TimeSyncMap ofApp::calculateTimeSyncMap(vector<TimestampData> timestampDa
 	//for (size_t i = 0; i < timestampData.size(); ) {
 	//	timestampData.
 	//}
-
+	int totalRttFound = 0;
 	// erase any blank lines
 	for (auto it = timestampData.begin(); it != timestampData.end(); ) {
-		if (it->roundTrip == -1) {
+		if (it->roundTrip < 0) {
+			ofLog(OF_LOG_NOTICE, "Removing -ve RTT: " + ofToString(it->roundTrip));
```
Comment (produceconsumerobot) [inline EmotiBitDataParser/src/ofApp.cpp:247]: What does -ve stand for?
Perhaps a clearer description of what's happening in the notice would be helpful.

**Comment by nitin710** [comment]
Addressing Review Comments
- [I'm unsure why the 2 nearest RTTs are being used instead of the 262351 and 2377788](https://github.com/EmotiBit/ofxEmotiBit/pull/106#issuecomment-1111604820)
  - [?]
- we need to look at parsed timestamp difference histograms that prove the timestamps are being parsed correctly.
  - [?
- I thought we were adding some smarts about Q1, Q2, Q3, Q4 selection in calculateTimeSyncMap() in this PR. Is that not the case?
  - [?]
- give the user instructive feedback on what went wrong, how it might impact their timestamps, and how to record better data next time
  - [?]
- https://github.com/EmotiBit/ofxEmotiBit/pull/106#discussion_r860366342
  - [?]
# Changelog
- Added parsing for 0 timestamps received
- Added parsing for 1 timestamp received
- smarts about choosing timestamps from quadrants
- Improved messaging 
- parsed data timestamp histograms
-

**Comment by nitin710** [comment]
# Timestamp Testing and analysis
| File | Condition | TimeSync histogram PI | Timesync histogram AX | Timesync histogram EA | Tiemsync histogram TH |
|-----|------------|---------------------------|----------------------------|--------------------------|---------------------------|
|Good example | Always connected, healthy amount of timestamp received|image|image |image |image ||bad example| 1 timestamp received in the beginning | | | | |
|bad example| 1 timestamp received in the end | | | | |
|bad example | 0 timestamps received | | | | |

File: EmotiBitDataParser/src/ofApp.h [hunk 5]
```diff
@@ -103,8 +104,8 @@ class ofApp : public ofBaseApp {
 	struct TimeSyncMap {
 		long double e0 = 0;
 		long double e1 = 0;
```
[the remark this answers is not in the document]
Comment (nitin710) [reply EmotiBitDataParser/src/ofApp.h:106]: Made the change

File: EmotiBitDataParser/src/ofApp.cpp [hunk 6]
```diff
@@ -191,20 +193,29 @@ void ofApp::update() {
...
-
-					string filename = inFileDir + inFileBase + "_" + "timeSyncMap" + fileExt;
-					cout << "Creating file: " << filename << endl;
-					ofstream mFile;
-					mFile.open(filename.c_str(), ios::out);
-					mFile << "e0,e1,c0,c1" << endl;
-					mFile << ofToString(timeSyncMap.e0, 6) << "," << ofToString(timeSyncMap.e1, 6) << "," << ofToString(timeSyncMap.c0, 6) << "," << ofToString(timeSyncMap.c1, 6);
-					mFile.close();
+					// check if enough time syncs were found to create a map.
+					if (timeSyncMap.e0 == 0 || timeSyncMap.e1 == 0)
```
[the remark this answers is not in the document]
Comment (nitin710) [reply EmotiBitDataParser/src/ofApp.cpp]: Look at #110

File: EmotiBitDataParser/src/ofApp.cpp [hunk 7]
```diff
@@ -396,9 +407,15 @@ void ofApp::draw() {
 	else if (currentState == State::PARSING_DATA) {
 		legendFont.drawString("PARSING_DATA: " + ofToString(lineCounter * 100.f / nLinesInFile, 0) + "% complete", 10, 100);
 	}
-
-	legendFont.drawString(dataLine, 10, 200);
-
+	else if (currentState == State::ERROR_INSUFFICIENT_TIMESYNCS)
+	{
+		ofSetColor(255, 0, 0);
+		legendFont.drawString("Cannot parse file\nERROR:INSUFFICIENT TIMESYNCS", 10, 100);
```
[the remark this answers is not in the document]
Comment (nitin710) [reply EmotiBitDataParser/src/ofApp.cpp]: check #111

File: EmotiBitDataParser/src/ofApp.cpp (hunk 4 above)
Comment (nitin710) [reply EmotiBitDataParser/src/ofApp.cpp]: changed. It was supposed to suggest erroneous RTTs
